---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-clone-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: amazon-prime-clone
  template:
    metadata:
      labels:
        app: amazon-prime-clone
    spec:
      containers:
      - name: amazon-prime-clone-container
        image: riyakatiyar/amazon-prime-clone
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-clone-service
spec:
  type: LoadBalancer
  selector:
    app: amazon-prime-clone
  ports:
  - port: 80
    targetPort: 3000
